implemented userdetails & added authorities
oksana-rudenko/online-book-store pull request #10
Opened 2023-12-14 21:14 UTC by oksana-rudenko

2023-12-15 13:32 UTC, kerrrusha requested changes

2023-12-15 13:32 UTC, kerrrusha commented on src/main/java/springboot/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
so admin would not have access to that endpoint?

2023-12-15 13:32 UTC, kerrrusha commented on src/main/java/springboot/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
so admin would not have access to that endpoint?

2023-12-15 19:09 UTC, sokimaaa commented on src/main/java/springboot/onlinebookstore/config/SecurityConfig.java
> +                                .requestMatchers("/auth/**", "/swagger-ui/**")
append with "/error" to allow users see error page

2023-12-15 19:10 UTC, sokimaaa commented on src/main/java/springboot/onlinebookstore/config/SecurityConfig.java
> +    }
You dont need to inject dependencies in such way when you use @Configuration and @Bean. 

You can directly inject via method params.
```suggestion
```

2023-12-15 19:14 UTC, sokimaaa commented on src/main/java/springboot/onlinebookstore/model/Role.java
> +public class Role {
Could the role be deleted or created?

You instantiate all roles in `RoleName`. 
And how your BookController will handle this? e.g. @PreAuthorize("hasRole('ROLE_ADMIN')")

2023-12-17 11:14 UTC, Sanderfuck approved these changes

2023-12-17 12:30 UTC, merged